# Generated by Django 5.1.6 on 2025-02-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_page_is_published_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='crated_at',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='updated_by',
        ),
    ]
