# Generated by Django 5.1.6 on 2025-02-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_crated_at_post_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_by',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_by',
            new_name='updated_at',
        ),
    ]
